config/routes.rb
Impel::Application.routes.draw do

  root 'posts#index'

  resources :posts do
    get 'page/:page', :action => :index, :on => :collection
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :source

  has_attached_file :image, styles: { thumb: '340' }

  def self.a_page(page_number=nil)
    Post.order("created_at DESC").page(page_number).per(25)
  end
end

app/models/source.rb
class Source < ActiveRecord::Base
  has_many :posts
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController
  def index
    @posts = Post.a_page(params[:page])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def main
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order("created_at DESC").page(params[:page]).per(25)
  end

  def show
    @post = Post.find(params[:id], :include => :source)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def image?(url)
    !(url =~ /\.(?:jpe?g|png|gif)$/i).nil?
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
    <meta charset="utf-8" />

    <!-- Uncomment to make IE8 render like IE7 -->
    <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

    <!-- Set the viewport width to device width for mobile -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= yield(:meta) %>
    <title><%= content_for?(:title) ? yield(:title) : "impel" %></title>

    <%= stylesheet_link_tag "application" %>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body>
    <%= render partial: 'shared/google_analytics' %>

    <nav class="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">impel</a></h1>
        </li>
      </ul>
    </nav>

    <%= yield %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/main.html.erb
<div id="container">Loading...</div>

app/views/posts/index.html.erb
<div class="pages">
  <h2><%= paginate @posts %></h2>
</div>

<div id="container" class="">
  <% @posts.each do |post| %>
    <div class="post">
        <%= link_to image_tag(post.image.url(:thumb)), post_path(post) %>
    </div>
  <% end %>
</div>

<div class="pages">
  <h2><%= paginate @posts %></h2>
</div>

app/views/posts/show.html.erb
<div id="post">
  <%= render partial: 'shared/social_buttons', locals: { post: @post } %>
  <div id="post-image">
    <%= link_to image_tag(@post.image.url(:original)), @post.original_url %>
  </div>
  <div id="post-meta">
    <p>
      Originally posted to <em><%= @post.source.title.titleize %></em>
      by <%= link_to @post.author_title, @post.author_url %>.
    </p>
  </div>
</div>

app/views/shared/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-41121479-1', 'impel.io');
  ga('send', 'pageview');

</script>

app/views/shared/_social_buttons.html.erb
<% content_for :meta, tag('meta', :property => 'og:image', :content => post.image.url(:original)) %>

<table id="social-buttons">
  <tr>
    <td><%= pinit_button(url: post_url(post), media: post.image.url(:original), description: "Impel Images") %></td>
    <td><%= like_button('465673663517478', href: post_url(post)) %></td>
    <td><%= tweet_button(count: 'horizontal', via: "impelio", url: post_url(post), text: "Impel Images: #{post_url(post)}") %></td>
  </tr>
</table>